workspace = name:Comms, monitor:DP-2
workspace = name:Steam, monitor:DP-2 
workspace = name:Forex, monitor:DP-2 

# Named workspaces for specific Apps
windowrule {
	name = Comms
	match:class = (.*[Dd]iscord.*|.*[Ss]ignal.*|.*[Ee]lement.*)

	workspace = name:Comms
}
bind =  $mainMod ALT, C, workspace, name:Comms 

windowrule {
	name = Steam
	match:class = (.*[Ss]team.*)

	workspace = name:Steam
}
bind =  $mainMod ALT, S, workspace, name:Steam 

windowrule {
	name = OTD
	match:class = (.*[Oo]pen[Tt]ablet[Dd]river.*)

	workspace = special:otd
}
bind =  $mainMod ALT, T, togglespecialworkspace, otd 

binds {
	workspace_back_and_forth = false
}

windowrule {
	name = Forex
	match:initial_title = (.*[Mm]eta[Tt]rader.*)

	workspace = name:Forex
}
bind =  $mainMod ALT, F, workspace, name:Forex
